name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Docker Compose files
      run: docker compose -f docker-compose-quickstart.yml up -d
    
    - name: Docker List Images
      run: docker images

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      
    - name: Tag and Push Docker Image
      run: |
        docker tag orbit-homework-store-front:latest ${{ secrets.ACR_REGISTRY }}/orbit-homework-store-front:latest
        docker push ${{ secrets.ACR_REGISTRY }}/orbit-homework-store-front:latest
        docker tag orbit-homework-product-service:latest ${{ secrets.ACR_REGISTRY }}/orbit-homework-product-service:latest
        docker push ${{ secrets.ACR_REGISTRY }}/orbit-homework-product-service:latest
        docker tag orbit-homework-order-service:latest ${{ secrets.ACR_REGISTRY }}/orbit-homework-order-service:latest
        docker push ${{ secrets.ACR_REGISTRY }}/orbit-homework-order-service:latest