name: Orbit Homework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bicep-plan:
    name: 'Bicep Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Plan
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
          az deployment sub create --location "East US 2" --template-file "/home/runner/work/orbit-homework/orbit-homework/infra/bicep/main.bicep" --what-if
  
  bicep-deployment:
    name: 'Bicep Deployment'
    runs-on: ubuntu-latest
    needs: bicep-plan
    environment: 'orbit-homework'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Deloyment
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
          az deployment sub create --location "East US 2" --template-file "/home/runner/work/orbit-homework/orbit-homework/infra/bicep/main.bicep"

