name: Azure Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Plan
      uses: azure/cli@v2
      with:
        azcliversion: latest
        working-directory: ./infra
        inlineScript: |
          pwd
