name: Orbit Homework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform Version
      run: terraform version

    - name: Terraform Init
      run: |
        cd infra/terraform
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
        pwd
        terraform init \
        -upgrade \
        -backend-config="resource_group_name=rg-orbittfstate-tst-use2-001" \
        -backend-config="storage_account_name=storbittfstate001" \
        -backend-config="container_name=orbit-tfstate" \
        -backend-config="key=orbit.tfstate"

    - name: Terraform Plan
      run: |
        cd infra/terraform
        terraform plan \
        -out=tfplan
        