name: Azure Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Plan
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          cd /home/runner/work/orbit-homework/orbit-homework/infra/bicep
          az deployment sub create --location "East US 2" --template-file ".\main.bicep" --what-if
