name: Orbit Homework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bicep-plan:
    name: 'Bicep Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Plan
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
          az deployment sub create --location "East US 2" --template-file "/home/runner/work/orbit-homework/orbit-homework/infra/bicep/main.bicep" --what-if
  
  bicep-deployment:
    name: 'Bicep Deployment'
    runs-on: ubuntu-latest
    needs: bicep-plan
    environment: 'orbit-homework'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Subscription
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Bicep Deloyment
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
          az bicep install
          az bicep version
          az deployment sub create --location "East US 2" --template-file "/home/runner/work/orbit-homework/orbit-homework/infra/bicep/main.bicep"

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: [bicep-plan, bicep-deployment]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Terraform Install'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform Version
      run: terraform version

    - name: Terraform Init
      run: |
        cd infra/terraform
        export ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
        export ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
        export ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}
        export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
        terraform init \
        -upgrade \
        -backend-config=storage_account_name=storbittfstate001 \
        -backend-config=container_name=orbit-tfstate \
        -backend-config=key=orbit.tfstate \
        -backend-config=resource_group_name=rg-orbittfstate-tst-use2-001 \